title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
# Build settings
remote_theme: huangyz0918/moving

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
